language: node_js

node_js:
  - 8

script:
  - npm run build

deploy:
  - provider: script
    script: npm run travis-deploy-once "npm run deploy"
    skip_cleanup: true
    on:
      branch: master

after_deploy:
  - npm run clean

notifications:
  email:
    on_failure: change

cache:
  npm: true
  directories:
    - node_modules
