version: 2

jobs:
  build:
    machine: true
    steps:
      # checkout code from github
      - checkout

      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: build the application image
          command: |
            docker build \
              --build-arg PORT=443 \
              --build-arg ADDRESS=realrockstars.io \
              --build-arg GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID \
              --build-arg GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET \
              -t davesnx/realrockstars.io:latest \
              -t davesnx/realrockstars.io:$CIRCLE_BUILD_NUM .

      - run:
          name: deploy the image and tag as latest
          command: |
            docker push davesnx/realrockstars.io:$CIRCLE_BUILD_NUM
            docker push davesnx/realrockstars.io:latest
            echo "https://hub.docker.com/r/davesnx/realrockstars.io/tags"
