version: 2
jobs:
  build:
    machine: true
    steps:
      # checkout code from github
      - checkout

      - run:
          name: login to docker hub
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: build the application image
          command: docker build -t realrockstars .

      - run:
          name: tag latest
          command: |
            docker tag realrockstars davesnx/realrockstars.io
            docker tag realrockstars davesnx/realrockstars.io:$CIRCLE_BUILD_NUM

      - run:
          name: deploy the image
          command: docker push davesnx/realrockstars.io
