version: 2
jobs:
  build:
    machine: true
    steps:
      # checkout code from github
      - checkout

      # login to docker hub
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

      # build the application image
      - run: docker build -t davesnx/realrockstars.io:$CIRCLE_BUILD_NUM .

      # deploy the image
      - run:
        - docker tag davesnx/realrockstars.io:$CIRCLE_BUILD_NUM davesnx/realrockstars.io:latest
        - docker push davesnx/realrockstars.io:$CIRCLE_BUILD_NUM
